export const parfums = [
    {
        fullArticle: 'm00350',
        originFor: 'Giorgio Armani Acqua di Gio',
        imageLogo: 'EssenceLogo.png',
        imageBottle: 'BottleMan01',
        parfumesFor: 'духи для мужчин',
        smallArticle: 'm003',
        description: 'Свежий легкий аромат, ароматные ноты которого воплощают свободу и независимость',
        topNotes: 'апельсин, лайм, мандарин, жасмин, бергамот, лимон',
        heartNotes: 'цикламен, мускатный орех, резеда, кориандр, фиалка, фрезия, морские нотки, персик, гиацинт, роза',
        baseNotes: 'амбра, пасули, дубовый мох, кедр, мускус',
        smell: 'ЦИТРУСОВЫЕ ВОДНЫЕ',
        status: 'В наличии'
    },
    {
        fullArticle: 'm01550',
        originFor: 'Chanel Bleu de Chanel',
        imageLogo: 'EssenceLogo.png',
        imageBottle: 'BottleMan01',
        parfumesFor: 'духи для мужчин',
        smallArticle: 'm015',
        description: 'Аромат власти и независимости',
        topNotes: 'лимон, апельсин, грейпфрут, розовый перец, ментол, мускатный орех',
        heartNotes: 'кедр, терпкие ноты, ветивер, имбирь, жасмин',
        baseNotes: 'пачули, ладан, сандал, лабданум',
        smell: 'ДРЕВЕСНЫЕ',
        status: 'В наличии'
    },
    {
        fullArticle: 'm04150',
        originFor: 'Carolina Herrera Bad Boy',
        imageLogo: 'EssenceLogo.png',
        imageBottle: 'BottleMan02',
        parfumesFor: 'духи для мужчин',
        smallArticle: 'm041',
        description: 'В этом парфюме вы можете найти страстный характер с оттенками элегантности и востока',
        topNotes: 'бергамот, перец',
        heartNotes: 'кедровое дерево, шалфей, лаванда',
        baseNotes: 'бобы тонка, амбровое дерево, какао',
        smell: 'ВОСТОЧНЫЕ ПРЯНЫЕ',
        status: 'В наличии'
    },
    {
        fullArticle: 'm04350',
        originFor: 'GIVENCHY Gentleman',
        imageLogo: 'EssenceLogo.png',
        imageBottle: 'BottleMan02',
        parfumesFor: 'духи для мужчин',
        smallArticle: 'm043',
        description: 'Парфюм полный контрастов, созданный для истинных джентльменов',
        topNotes: 'бергамот, зеленые тоны, кардамон, ананас',
        heartNotes: 'лаванда, ирис, герань, мох',
        baseNotes: 'пачули, кожа, ваниль',
        smell: 'ФУЖЕРНЫЕ',
        status: 'В наличии'
    },
    {
        fullArticle: 'W10250',
        originFor: 'LANVINE Eclat D’Arpege',
        imageLogo: 'EssenceLogo.png',
        imageBottle: 'BottleWoman01',
        parfumesFor: 'духи для женщин',
        smallArticle: 'W102',
        description: 'Этот аромат будет сопровождать свою хозяйку повсюду, подчеркивая обаяние и красоту',
        topNotes: 'зеленая сирень, листья сицилийского лимона',
        heartNotes: 'цветок персика, глициния, красный пион, зеленый чай, османтус',
        baseNotes: 'амбра, мускус, кедр',
        smell: 'ЦВЕТОЧНЫЕ ЗЕЛЕНЫЕ',
        present: false
    },
    {
        fullArticle: 'W10450',
        originFor: 'Dolce & Gabbana  Light Blue',
        imageLogo: 'EssenceLogo.png',
        imageBottle: 'BottleWoman01',
        parfumesFor: 'духи для женщин',
        smallArticle: 'W104',
        description: 'Аромат радости жизни, который окутает вас свежестью.',
        topNotes: 'сицилийский лимон, кедр, зеленое яблоко, колокольчик',
        heartNotes: 'белая роза, бамбук, жасмин',
        baseNotes: 'кедр, мускус, амбра',
        smell: 'ЦВЕТОЧНЫЕ ФРУКТОВЫЕ',
        status: 'В наличии'
    },
    {
        fullArticle: 'W11150',
        originFor: 'Versace Bright Crystal',
        imageLogo: 'EssenceLogo.png',
        imageBottle: 'BottleWoman01',
        parfumesFor: 'духи для женщин',
        smallArticle: 'W111',
        description: 'Бесценный вклад, который таит в себе нежную чувственность и кристальную чистоту.',
        topNotes: 'гранат, юзу',
        heartNotes: 'пион, магнолия, лотос',
        baseNotes: 'амбра, мускус',
        smell: 'ЦВЕТОЧНЫЕ ФРУКТОВЫЕ',
        status: 'В наличии'
    },
    {
        fullArticle: 'W11650',
        originFor: 'Lacoste Pour Femme',
        imageLogo: 'EssenceLogo.png',
        imageBottle: 'BottleWoman01',
        parfumesFor: 'духи для женщин',
        smallArticle: 'W116',
        description: 'Игривый аромат, его ароматные ноты представляют собой праздник и спонтанность',
        topNotes: 'ямайский перец, фрезия, яблоко',
        heartNotes: 'фиалка, гибискус, жасмин, гелиотроп, роза',
        baseNotes: 'лабданум, сандаловое дерево, ладан, кедр, мох',
        smell: 'ЦВЕТОЧНЫЕ ДРЕВЕСНЫЕ МУСКУСНЫЕ',
        status: 'В наличии'
    },
    {
        fullArticle: 'W11850',
        originFor: 'Christian Dior J’adore',
        imageLogo: 'EssenceLogo.png',
        imageBottle: 'BottleWoman01',
        parfumesFor: 'духи для женщин',
        smallArticle: 'W118',
        description: 'Выразительный женский аромат, который сочетает в себе простоту и элегантность.',
        topNotes: 'мандарин, роза, африканская орхидея',
        heartNotes: 'ежевика, слива, фиалка',
        baseNotes: 'мускус, амарантовое дерево, плющ',
        smell: 'ЦВЕТОЧНЫЕ ФРУКТОВЫЕ',
        status: 'В наличии'
    },
    {
        fullArticle: 'W13050',
        originFor: 'ESCADA Modn Sparkle',
        imageLogo: 'EssenceLogo.png',
        imageBottle: 'BottleWoman01',
        parfumesFor: 'духи для женщин',
        smallArticle: 'W130',
        description: 'Цветочный аромат для амбициозной женщины, которая не забывает о своем природном шарме',
        topNotes: 'черная смородина, цитрусовые, земляника, красное яблоко',
        heartNotes: 'фрезия, душистый горошек, жасмин, роза',
        baseNotes: 'сандаловое дерево, амбра, мускус, малина',
        smell: 'ЦВЕТОЧНЫЕ ФРУКТОВЫЕ',
        status: 'В наличии'
    },
    {
        fullArticle: 'W14250',
        originFor: 'YVES SAINT LAURENT Black Opium',
        imageLogo: 'EssenceLogo.png',
        imageBottle: 'BottleWoman01',
        parfumesFor: 'духи для женщин',
        smallArticle: 'W142',
        description: 'Чувственный и таинственный аромат, полный традиций, классических, сладких и кофейных ароматов для необузданных женщин',
        topNotes: 'груша, цветы апельсинового дерева, розовый перец',
        heartNotes: 'жасмин, ветивер',
        baseNotes: 'пачули, кедр, ваниль',
        smell: 'ВОСТОЧНЫЕ',
        status: 'В наличии'
    },
    {
        fullArticle: 'W14850',
        originFor: 'Giorgio Armani Si',
        imageLogo: 'EssenceLogo.png',
        imageBottle: 'BottleWoman01',
        parfumesFor: 'духи для женщин',
        smallArticle: 'W148',
        description: 'Нежный женский парфюм для обладательниц беззаботной молодости и позитивных эмоций',
        topNotes: 'черная смородина',
        heartNotes: 'цветы, фрезия, цветущая роза',
        baseNotes: 'ваниль, пачули, амброксид (амбровый запах с лёгким древесным оттенком)',
        smell: 'ЦВЕТОЧНЫЕ ШИПРОВЫЕ',
        status: 'В наличии'
    },
    {
        fullArticle: 'W15050',
        originFor: 'Paco Rabanne Olympea',
        imageLogo: 'EssenceLogo.png',
        imageBottle: 'BottleWoman01',
        parfumesFor: 'духи для женщин',
        smallArticle: 'W150',
        description: 'Парфюм подчеркивает природную красоту и элегантность с нежным оттенком женской соблазнительности и игривости.',
        topNotes: 'имбирь, жасмин, мандарин',
        heartNotes: 'ваниль, соль',
        baseNotes: 'амбра, кашемир, сандаловое дерево',
        smell: 'ЦВЕТОЧНЫЕ',
        status: 'В наличии'
    },
    {
        fullArticle: 'W15150',
        originFor: 'Carolina Herrera Good Girl',
        imageLogo: 'EssenceLogo.png',
        imageBottle: 'BottleWoman01',
        parfumesFor: 'духи для женщин',
        smallArticle: 'W151',
        description: 'Завораживающие ароматы образуют идеальное гармоничное целое и придают женщине смелость, элегантность и непостижимую тайну',
        topNotes: 'миндаль, зеленые ноты, перец, черная смородина',
        heartNotes: 'ландыш, жасмин, тубероза',
        baseNotes: 'бобы Тонка, какао, амбра',
        smell: 'ЦВЕТОЧНЫЕ',
        status: 'В наличии'
    },
    {
        fullArticle: 'W15350',
        originFor: 'D&G L’Imperatrice 3',
        imageLogo: 'EssenceLogo.png',
        imageBottle: 'BottleWoman01',
        parfumesFor: 'духи для женщин',
        smallArticle: 'W153',
        description: 'Уверенный, страстный аромат олицетворяет силу и индивидуальность чувственной, современной и независимой женщины, которая не боится высказать свое мнение',
        topNotes: 'арбуз, киви',
        heartNotes: 'цветочные ноты, цикламен',
        baseNotes: 'дерево, мускус',
        smell: 'ЦВЕТОЧНЫЕ',
        status: 'В наличии'
    },
    {
        fullArticle: 'W15950',
        originFor: 'Escentric  Molecules 02',
        imageLogo: 'EssenceLogo.png',
        imageBottle: 'BottleWoman01',
        parfumesFor: 'духи для женщин',
        smallArticle: 'W159n',
        description: 'Постепенно раскрываясь, придает нежный и чувственный аромат, который подходит как мужчинам, так и женщинам',
        topNotes: 'цитрусы',
        heartNotes: 'цветы',
        baseNotes: 'дерево, мускус',
        smell: 'ДРЕВЕСНЫЕ',
        status: 'В наличии'
    },
    {
        fullArticle: 'W17250',
        originFor: 'Yves saint laurent libre',
        imageLogo: 'EssenceLogo.png',
        imageBottle: 'BottleWoman01',
        parfumesFor: 'духи для женщин',
        smallArticle: 'W172',
        description: 'Создан для независимой и уверенной в себе женщины, которая идет против стереотипов и настроена ради своей свободы сделать что угодно.',
        topNotes: 'мандарин, апельсин',
        heartNotes: 'жасмин, кедровое дерево',
        baseNotes: 'мускус, пудровые тона',
        smell: 'ЦВЕТОЧНЫЕ ЦИТРУСОВЫЕ',
        status: 'В наличии'
    },
    {
        fullArticle: 'W17350',
        originFor: 'Jo Malone English Pear & Freesia',
        imageLogo: 'EssenceLogo.png',
        imageBottle: 'BottleWoman01',
        parfumesFor: 'духи для женщин',
        smallArticle: 'W173',
        description: 'Этот чистый аромат с оттенком роскоши создан для уверенных в себе и чувственных женщин с утонченным вкусом.',
        topNotes: 'груша, арбуз, бергамот',
        heartNotes: 'фрезия, роза, ландыш',
        baseNotes: 'мускус, пачули, белые цветы',
        smell: 'ЦВЕТОЧНЫЕ ЦИТРУСОВЫЕ',
        status: 'В наличии'
    },
    {
        fullArticle: 'W17650',
        originFor: 'VERSACE Crystal Noire',
        imageLogo: 'EssenceLogo.png',
        imageBottle: 'BottleWoman01',
        parfumesFor: 'духи для женщин',
        smallArticle: 'W176',
        description: 'кокетливый, неприступный, респектабельный хулиганский, денежный',
        topNotes: 'имбирь, кардамон, перец',
        heartNotes: 'цветы африканского апельсина, гардения, пион',
        baseNotes: 'мускус, сандал, амбра',
        smell: 'ЦВЕТОЧНЫЕ ДРЕВЕСНЫЕ',
        status: 'В наличии'
    },
    {
        fullArticle: 'W16250',
        originFor: 'CAROLINA HERRERA 212 VIP Party Fever',
        imageLogo: 'EssenceLogo.png',
        imageBottle: 'BottleWoman01',
        parfumesFor: 'духи для женщин',
        smallArticle: 'W162',
        description: 'Чувственный фруктовый аромат пробуждает вас спонтанностью и переписывает правила. Это беззаботный аромат, подходящий для лучших вечеринок.',
        topNotes: 'малина, лакрица',
        heartNotes: 'жасмин, морские ноты',
        baseNotes: 'мускус, сандаловое дерево, древесные ноты',
        smell: 'ЦВЕТОЧНЫЕ ФРУКТОВЫЕ',
        status: 'В наличии'
    },
    {
        fullArticle: 'W18050',
        originFor: 'Yves saint laurent Manifesto',
        imageLogo: 'EssenceLogo.png',
        imageBottle: 'BottleWoman01',
        parfumesFor: 'духи для женщин',
        smallArticle: 'W180',
        description: 'Восточно-цветочный аромат, олицетворяющий смелую женщину',
        topNotes: 'черная смородина, бергамот, зеленые тона',
        heartNotes: 'ландыш, жасмин самбак',
        baseNotes: 'кедр, сандал, ваниль, бобы тонка',
        smell: 'ВОСТОЧНЫЕ ЦВЕТОЧНЫЕ',
        status: 'В наличии'
    },
    {
        fullArticle: 'W18550',
        originFor: 'Christian Dior Joy by Dior Intence',
        imageLogo: 'EssenceLogo.png',
        imageBottle: 'BottleWoman185',
        parfumesFor: 'духи для женщин',
        smallArticle: 'W185',
        description: 'Аромат привлекателен для женщин, которые ищут баланс между свежестью и нежной чувственностью',
        topNotes: 'бергамот, мандарин, апельсин',
        heartNotes: 'роза, жасмин',
        baseNotes: 'сандаловое и кедровое дерево, пачули, мускус',
        smell: 'ЦИТРУСОВЫЕ ЦВЕТОЧНЫЕ',
        status: 'В наличии'
    },
    {
        fullArticle: 'W18650',
        originFor: 'Jo Malone Lime Basil & Mandarin',
        imageLogo: 'EssenceLogo.png',
        imageBottle: 'BottleWoman186',
        parfumesFor: 'духи для женщин',
        smallArticle: 'W186',
        description: 'Отличная новость для всех любительниц свежести. Вы ощущаете этот приятный аромат цитрусовых с необычным базиликом?',
        topNotes: 'мандарин, лайм, грейпфрут, базилик, бергамот',
        heartNotes: 'мята, яблоко, слива, жасмин',
        baseNotes: 'кедровое дерево, пачули, ветивер, мох',
        smell: 'ЦИТРУСОВЫЕ ДРЕВЕСНЫЕ',
        status: 'В наличии'
    },
    {
        fullArticle: 'W19050',
        originFor: 'Yves Saint Laurent PARISIENNE',
        imageLogo: 'EssenceLogo.png',
        imageBottle: 'BottleWoman190',
        parfumesFor: 'духи для женщин',
        smallArticle: 'W190',
        description: 'Утонченное и гармоничное сочетание разных ингредиентов, которые, несмотря на это, создают выразительный и нежный чувственный эффект',
        topNotes: 'малина, клюква',
        heartNotes: 'роза, фиалка, пион',
        baseNotes: 'мускус, сандаловое дерево, ветивер, пачули',
        smell: 'ЦВЕТОЧНЫЕ ДРЕВЕСНЫЕ',
        status: 'В наличии'
    },
    {
        fullArticle: 'W4el04',
        originFor: 'ESSENS 4 ELEMENTS - Purple Air',
        imageLogo: 'EssenceLogo.png',
        imageBottle: '4el04',
        parfumesFor: 'унисекс',
        smallArticle: '4el04',
        description: 'Унисекс-аромат как легкий ветерок и порыв ветра: свободный, нежный, упрямый и полный сил',
        topNotes: 'перец, гвоздика, бергамот, тмин',
        heartNotes: 'жасмин',
        baseNotes: 'древесные ноты, мускус',
        smell: '',
        status: 'В наличии'
    },
    {
        fullArticle: 'm03750',
        originFor: 'Jo Malone Oud & Bergamot Cologne Intense',
        imageLogo: 'EssenceLogo.png',
        imageBottle: 'BottleMan01',
        parfumesFor: 'духи для мужчин',
        smallArticle: 'm037',
        description: 'Загадочный дымный характер добавлен древесными тонами, редким мускусом и амброй',
        topNotes: 'бергамот, лимон, апельсин',
        heartNotes: 'лавандин, жасмин',
        baseNotes: 'древесные тона, пачули, мускус, амбра',
        smell: 'ЦИТРУСОВЫЕ ДРЕВЕСНЫЕ',
        status: 'В наличии'
    },
    {
        fullArticle: 'm03850',
        originFor: 'Jo Malone London Earl Grey & Cucumber',
        imageLogo: 'EssenceLogo.png',
        imageBottle: 'BottleMan01',
        parfumesFor: 'духи для мужчин',
        smallArticle: 'm038',
        description: 'В самом начале вы будете освежены взрывами бергамота и цитрусовых, которые дополняют тона трав и искрящегося жасмина в их сердцах, а мускус и теплые древесные тона добавляют изысканности',
        topNotes: 'бергамот, апельсин',
        heartNotes: 'зелень, жасмин',
        baseNotes: 'мускус, древесные тона',
        smell: 'ЦИТРУСОВЫЕ ЦВЕТОЧНЫЕ',
        present: false
    },
    {
        fullArticle: 'm03950',
        originFor: 'Narciso Rodriguez Blue noir for him',
        imageLogo: 'EssenceLogo.png',
        imageBottle: 'BottleMan01',
        parfumesFor: 'духи для мужчин',
        smallArticle: 'm039',
        description: 'Горький грейпфрут и свежая сладость бергамота раскроют вашу смелость, тона кедра и пачули укажут на вашу силу, а мускусный мох подчеркнет вашу природную мужественность.',
        topNotes: 'бергамот, грейпфрут',
        heartNotes: 'кедр, пачули',
        baseNotes: 'дубовый мох, мускус',
        smell: 'ДРЕВЕСНЫЕ ЦИТРУСОВЫЕ',
        status: 'В наличии'
    },

]